FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/zibon-ceramic/firestore/indexes?
fix tit